// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package objs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfConnectRequest struct {
	_     structs.HostLayout
	Daddr uint32
	Dport uint16
	Proto uint16
}

type BpfCorrelationContext struct {
	_    structs.HostLayout
	Tgid uint32
	Pid  uint32
	Gid  uint32
	Uid  uint32
}

type BpfCounter struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	Next uint32
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	X64SysSetuid      *ebpf.ProgramSpec `ebpf:"__x64_sys_setuid"`
	BprmCheckSecurity *ebpf.ProgramSpec `ebpf:"bprm_check_security"`
	CredPrepare       *ebpf.ProgramSpec `ebpf:"cred_prepare"`
	FileOpen          *ebpf.ProgramSpec `ebpf:"file_open"`
	RestrictConnect   *ebpf.ProgramSpec `ebpf:"restrict_connect"`
	SocketBind        *ebpf.ProgramSpec `ebpf:"socket_bind"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	CorrelationContexts  *ebpf.MapSpec `ebpf:"correlation_contexts"`
	CounterMapConnect    *ebpf.MapSpec `ebpf:"counter_map_connect"`
	CounterMapMirror     *ebpf.MapSpec `ebpf:"counter_map_mirror"`
	CounterMapSleep      *ebpf.MapSpec `ebpf:"counter_map_sleep"`
	RequestArrayConnect  *ebpf.MapSpec `ebpf:"request_array_connect"`
	RequestArrayMirror   *ebpf.MapSpec `ebpf:"request_array_mirror"`
	RequestArraySleep    *ebpf.MapSpec `ebpf:"request_array_sleep"`
	ResponseArrayConnect *ebpf.MapSpec `ebpf:"response_array_connect"`
	ResponseArrayMirror  *ebpf.MapSpec `ebpf:"response_array_mirror"`
	ResponseArraySleep   *ebpf.MapSpec `ebpf:"response_array_sleep"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	Pid          *ebpf.VariableSpec `ebpf:"pid"`
	TargetCgroup *ebpf.VariableSpec `ebpf:"target_cgroup"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	CorrelationContexts  *ebpf.Map `ebpf:"correlation_contexts"`
	CounterMapConnect    *ebpf.Map `ebpf:"counter_map_connect"`
	CounterMapMirror     *ebpf.Map `ebpf:"counter_map_mirror"`
	CounterMapSleep      *ebpf.Map `ebpf:"counter_map_sleep"`
	RequestArrayConnect  *ebpf.Map `ebpf:"request_array_connect"`
	RequestArrayMirror   *ebpf.Map `ebpf:"request_array_mirror"`
	RequestArraySleep    *ebpf.Map `ebpf:"request_array_sleep"`
	ResponseArrayConnect *ebpf.Map `ebpf:"response_array_connect"`
	ResponseArrayMirror  *ebpf.Map `ebpf:"response_array_mirror"`
	ResponseArraySleep   *ebpf.Map `ebpf:"response_array_sleep"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.CorrelationContexts,
		m.CounterMapConnect,
		m.CounterMapMirror,
		m.CounterMapSleep,
		m.RequestArrayConnect,
		m.RequestArrayMirror,
		m.RequestArraySleep,
		m.ResponseArrayConnect,
		m.ResponseArrayMirror,
		m.ResponseArraySleep,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	Pid          *ebpf.Variable `ebpf:"pid"`
	TargetCgroup *ebpf.Variable `ebpf:"target_cgroup"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	X64SysSetuid      *ebpf.Program `ebpf:"__x64_sys_setuid"`
	BprmCheckSecurity *ebpf.Program `ebpf:"bprm_check_security"`
	CredPrepare       *ebpf.Program `ebpf:"cred_prepare"`
	FileOpen          *ebpf.Program `ebpf:"file_open"`
	RestrictConnect   *ebpf.Program `ebpf:"restrict_connect"`
	SocketBind        *ebpf.Program `ebpf:"socket_bind"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.X64SysSetuid,
		p.BprmCheckSecurity,
		p.CredPrepare,
		p.FileOpen,
		p.RestrictConnect,
		p.SocketBind,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
